-- QueueFlow Oracle schema

CREATE TABLE queues (
    queue_code      VARCHAR2(32) PRIMARY KEY,
    display_name_en VARCHAR2(256) NOT NULL,
    display_name_zh VARCHAR2(256) NOT NULL,
    sort_order      NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE tickets (
    ticket_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code       VARCHAR2(32) NOT NULL,
    queue_code        VARCHAR2(32) NOT NULL,
    status            VARCHAR2(32) DEFAULT 'ACTIVE' NOT NULL,
    position_num      NUMBER DEFAULT 0 NOT NULL,
    highlighted_until TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_tickets_code UNIQUE (ticket_code),
    CONSTRAINT fk_tickets_queue FOREIGN KEY (queue_code) REFERENCES queues (queue_code)
);

CREATE INDEX idx_tickets_queue_status ON tickets (queue_code, status, position_num);

CREATE TABLE announcements (
    announcement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en        VARCHAR2(512),
    title_zh        VARCHAR2(512),
    body_en         CLOB,
    body_zh         CLOB,
    is_active       NUMBER(1) DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE footer_messages (
    footer_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_text CLOB NOT NULL,
    sort_order   NUMBER DEFAULT 0 NOT NULL,
    is_active    NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE speech_events (
    event_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code   VARCHAR2(32) NOT NULL,
    queue_code    VARCHAR2(32),
    language_code VARCHAR2(16) NOT NULL,
    speech_text   VARCHAR2(1024) NOT NULL,
    is_played     NUMBER(1) DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_speech_unplayed ON speech_events (is_played, created_at);

CREATE TABLE app_settings (
    setting_key   VARCHAR2(128) PRIMARY KEY,
    setting_value VARCHAR2(2048)
);

INSERT INTO queues (queue_code, display_name_en, display_name_zh, sort_order)
SELECT 'HANDIN', 'Hand-In Articles Counter', '交來物品窗口', 1 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM queues WHERE queue_code = 'HANDIN');

INSERT INTO queues (queue_code, display_name_en, display_name_zh, sort_order)
SELECT 'SECURITY', 'Start Visit', '開始探訪', 2 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM queues WHERE queue_code = 'SECURITY');

INSERT INTO queues (queue_code, display_name_en, display_name_zh, sort_order)
SELECT 'WAITING', 'Waiting Ticket No', '等候籌號', 3 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM queues WHERE queue_code = 'WAITING');

INSERT INTO footer_messages (message_text, sort_order, is_active)
SELECT 'Positions in the queue are generated automatically and are approximate only. Actual wait times may vary due to high demand, staffing levels, and operational requirements. Thank you for your patience. · 排隊位置由系統自動生成，僅供參考。實際等待時間可能會因需求量大、人手不足或不可預見的情況而有所不同', 1, 1
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM footer_messages);

INSERT INTO app_settings (setting_key, setting_value)
SELECT 'display.poll.interval.ms', '3000' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE setting_key = 'display.poll.interval.ms');

INSERT INTO app_settings (setting_key, setting_value)
SELECT 'ticket.highlight.duration.ms', '30000' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE setting_key = 'ticket.highlight.duration.ms');

INSERT INTO app_settings (setting_key, setting_value)
SELECT 'speech.default.language', 'zh-HK' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM app_settings WHERE setting_key = 'speech.default.language');
